namespace Honua.DevOps.Agent.Operations.Troubleshooting;

internal enum FaultCategory
{
    IngressGateway,
    DnsRouting,
    TlsCertificate,
    SecretCredential,
    PostgresConnectivity,
    PostgresPerformance,
    RedisConnectivity,
    ObjectStoragePermission,
    RolloutReadiness,
    GitOpsDrift,
    OidcAuth,
    WafRateLimit,
    ResourcePressure,
    BackgroundJobMigration,
    ObservabilityPath,
    BackupRestore,
    VpcNetworking,
    IamPermission,
    KubernetesRbac,
    ManagedIdentity,
    RedisPerformance,
    StorageLifecycle,
    LambdaCompute,
    ComputeQuota,
    SpatialData,
    LayerPublishing,
    TenantIsolation,
    SchemaIncompatibility,
    GitOpsSync,
    ReleaseGate,
    OperatorPolicy,
    ConnectionPooler,
    PersistentVolume,
    HelmDeployment,
    TerraformState,
    ContainerRegistry,
    DisasterRecovery,
    ApiGateway,
    NetworkFirewall,
    AgentRuntime,
    NamespaceManagement
}

internal static class FaultCategoryExtensions
{
    internal static string ToConfigValue(this FaultCategory category)
    {
        return category switch
        {
            FaultCategory.IngressGateway => "ingress-gateway",
            FaultCategory.DnsRouting => "dns-routing",
            FaultCategory.TlsCertificate => "tls-certificate",
            FaultCategory.SecretCredential => "secret-credential",
            FaultCategory.PostgresConnectivity => "postgres-connectivity",
            FaultCategory.PostgresPerformance => "postgres-performance",
            FaultCategory.RedisConnectivity => "redis-connectivity",
            FaultCategory.ObjectStoragePermission => "object-storage-permission",
            FaultCategory.RolloutReadiness => "rollout-readiness",
            FaultCategory.GitOpsDrift => "gitops-drift",
            FaultCategory.OidcAuth => "oidc-auth",
            FaultCategory.WafRateLimit => "waf-rate-limit",
            FaultCategory.ResourcePressure => "resource-pressure",
            FaultCategory.BackgroundJobMigration => "background-job-migration",
            FaultCategory.ObservabilityPath => "observability-path",
            FaultCategory.BackupRestore => "backup-restore",
            FaultCategory.VpcNetworking => "vpc-networking",
            FaultCategory.IamPermission => "iam-permission",
            FaultCategory.KubernetesRbac => "kubernetes-rbac",
            FaultCategory.ManagedIdentity => "managed-identity",
            FaultCategory.RedisPerformance => "redis-performance",
            FaultCategory.StorageLifecycle => "storage-lifecycle",
            FaultCategory.LambdaCompute => "lambda-compute",
            FaultCategory.ComputeQuota => "compute-quota",
            FaultCategory.SpatialData => "spatial-data",
            FaultCategory.LayerPublishing => "layer-publishing",
            FaultCategory.TenantIsolation => "tenant-isolation",
            FaultCategory.SchemaIncompatibility => "schema-incompatibility",
            FaultCategory.GitOpsSync => "gitops-sync",
            FaultCategory.ReleaseGate => "release-gate",
            FaultCategory.OperatorPolicy => "operator-policy",
            FaultCategory.ConnectionPooler => "connection-pooler",
            FaultCategory.PersistentVolume => "persistent-volume",
            FaultCategory.HelmDeployment => "helm-deployment",
            FaultCategory.TerraformState => "terraform-state",
            FaultCategory.ContainerRegistry => "container-registry",
            FaultCategory.DisasterRecovery => "disaster-recovery",
            FaultCategory.ApiGateway => "api-gateway",
            FaultCategory.NetworkFirewall => "network-firewall",
            FaultCategory.AgentRuntime => "agent-runtime",
            FaultCategory.NamespaceManagement => "namespace-management",
            _ => "unknown"
        };
    }
}
