#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

PROVIDER="codex"
OUTPUT_PATH="$REPO_ROOT/.env.local"
RUN_PREFLIGHT="false"
FORCE="false"
TERRAFORM_LOCAL_PATH="$REPO_ROOT/../honua-terraform"
HONUA_API_BASE_URL="http://localhost:8080"
OTEL_BASE_URL="http://localhost:4318"
HONUA_API_KEY=""
OTEL_API_KEY=""
CODEX_MODEL=""
CODEX_API_KEY=""
CODEX_ENDPOINT=""
CLAUDE_MODEL=""
CLAUDE_API_KEY=""
CLAUDE_ENDPOINT=""

usage() {
  cat <<'EOF'
Usage:
  scripts/bootstrap-operator-env.sh [options]

Options:
  --provider <codex|claude>           Default: codex
  --output <path>                     Default: .env.local in the repo root
  --terraform-local-path <path>       Default: ../honua-terraform
  --honua-api-base-url <url>          Default: http://localhost:8080
  --otel-base-url <url>               Default: http://localhost:4318
  --honua-api-key <value>             Optional
  --otel-api-key <value>              Optional
  --codex-model <value>               Optional
  --codex-api-key <value>             Optional
  --codex-endpoint <url>              Optional
  --claude-model <value>              Optional
  --claude-api-key <value>            Optional
  --claude-endpoint <url>             Optional
  --run-preflight                     Run dotnet preflight after writing the file
  --force                             Overwrite existing file
  --help                              Show help
EOF
}

require_value() {
  local flag="$1"
  local value="${2:-}"
  if [[ -z "$value" ]]; then
    echo "[ERROR] $flag requires a value" >&2
    exit 1
  fi
}

dotenv_escape() {
  local value="$1"
  if [[ -z "$value" ]]; then
    printf ''
    return
  fi

  if [[ "$value" =~ [[:space:]#\"\'\\] ]]; then
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    value="${value//$'\n'/\\n}"
    value="${value//$'\r'/\\r}"
    value="${value//$'\t'/\\t}"
    printf '"%s"' "$value"
    return
  fi

  printf '%s' "$value"
}

write_env_var() {
  local key="$1"
  local value="$2"
  printf '%s=%s\n' "$key" "$(dotenv_escape "$value")" >> "$OUTPUT_PATH"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --provider)
      require_value "$1" "${2:-}"
      PROVIDER="$2"
      shift 2
      ;;
    --output)
      require_value "$1" "${2:-}"
      OUTPUT_PATH="$2"
      shift 2
      ;;
    --terraform-local-path)
      require_value "$1" "${2:-}"
      TERRAFORM_LOCAL_PATH="$2"
      shift 2
      ;;
    --honua-api-base-url)
      require_value "$1" "${2:-}"
      HONUA_API_BASE_URL="$2"
      shift 2
      ;;
    --otel-base-url)
      require_value "$1" "${2:-}"
      OTEL_BASE_URL="$2"
      shift 2
      ;;
    --honua-api-key)
      require_value "$1" "${2:-}"
      HONUA_API_KEY="$2"
      shift 2
      ;;
    --otel-api-key)
      require_value "$1" "${2:-}"
      OTEL_API_KEY="$2"
      shift 2
      ;;
    --codex-model)
      require_value "$1" "${2:-}"
      CODEX_MODEL="$2"
      shift 2
      ;;
    --codex-api-key)
      require_value "$1" "${2:-}"
      CODEX_API_KEY="$2"
      shift 2
      ;;
    --codex-endpoint)
      require_value "$1" "${2:-}"
      CODEX_ENDPOINT="$2"
      shift 2
      ;;
    --claude-model)
      require_value "$1" "${2:-}"
      CLAUDE_MODEL="$2"
      shift 2
      ;;
    --claude-api-key)
      require_value "$1" "${2:-}"
      CLAUDE_API_KEY="$2"
      shift 2
      ;;
    --claude-endpoint)
      require_value "$1" "${2:-}"
      CLAUDE_ENDPOINT="$2"
      shift 2
      ;;
    --run-preflight)
      RUN_PREFLIGHT="true"
      shift
      ;;
    --force)
      FORCE="true"
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "[ERROR] Unknown arg: $1" >&2
      usage
      exit 1
      ;;
  esac
done

case "$PROVIDER" in
  codex|claude) ;;
  *)
    echo "[ERROR] provider must be `codex` or `claude`" >&2
    exit 1
    ;;
esac

case "$OUTPUT_PATH" in
  /*) ;;
  *) OUTPUT_PATH="$REPO_ROOT/$OUTPUT_PATH" ;;
esac

mkdir -p "$(dirname "$OUTPUT_PATH")"
if [[ -e "$OUTPUT_PATH" && "$FORCE" != "true" ]]; then
  echo "[ERROR] output file exists: $OUTPUT_PATH (use --force to overwrite)" >&2
  exit 2
fi

cat > "$OUTPUT_PATH" <<EOF
# Generated by scripts/bootstrap-operator-env.sh
# honua-devops auto-loads .env and .env.local from the working directory.
# Keep .env.example as the full reference template; use this file for local overrides.

EOF

write_env_var "HONUA_DEVOPS_PROVIDER" "$PROVIDER"
write_env_var "HONUA_DEVOPS_EXECUTION_MODE" "plan"
write_env_var "HONUA_DEVOPS_EXECUTION_TIER" "plan"
write_env_var "HONUA_DEVOPS_APPROVAL_MODE" "pr-first"
write_env_var "HONUA_DEVOPS_GITOPS_TOOL" "honua-gitops"
write_env_var "HONUA_DEVOPS_TERRAFORM_LOCAL_PATH" "$TERRAFORM_LOCAL_PATH"
write_env_var "HONUA_DEVOPS_HONUA_API_BASE_URL" "$HONUA_API_BASE_URL"
write_env_var "HONUA_DEVOPS_OTEL_BASE_URL" "$OTEL_BASE_URL"
write_env_var "HONUA_DEVOPS_HONUA_API_KEY" "$HONUA_API_KEY"
write_env_var "HONUA_DEVOPS_OTEL_API_KEY" "$OTEL_API_KEY"

{
  printf '\n# Selected provider placeholders\n'
} >> "$OUTPUT_PATH"

write_env_var "HONUA_DEVOPS_CODEX_MODEL" "$CODEX_MODEL"
write_env_var "HONUA_DEVOPS_CODEX_API_KEY" "$CODEX_API_KEY"
write_env_var "HONUA_DEVOPS_CODEX_ENDPOINT" "$CODEX_ENDPOINT"
write_env_var "HONUA_DEVOPS_CLAUDE_MODEL" "$CLAUDE_MODEL"
write_env_var "HONUA_DEVOPS_CLAUDE_API_KEY" "$CLAUDE_API_KEY"
write_env_var "HONUA_DEVOPS_CLAUDE_ENDPOINT" "$CLAUDE_ENDPOINT"

echo "Wrote bootstrap env overrides to: $OUTPUT_PATH"

output_basename="$(basename "$OUTPUT_PATH")"
if [[ "$output_basename" != ".env" && "$output_basename" != ".env.local" ]]; then
  echo "[WARN] $OUTPUT_PATH will not be auto-loaded by normal runs unless you source it or rename it to .env/.env.local." >&2
fi

if [[ ! -d "$TERRAFORM_LOCAL_PATH" ]]; then
  echo "[WARN] terraform local path does not exist yet: $TERRAFORM_LOCAL_PATH" >&2
fi

if [[ "$PROVIDER" == "codex" && ( -z "$CODEX_MODEL" || -z "$CODEX_API_KEY" ) ]]; then
  echo "[WARN] codex is selected but HONUA_DEVOPS_CODEX_MODEL/API_KEY are still empty." >&2
fi

if [[ "$PROVIDER" == "claude" && ( -z "$CLAUDE_MODEL" || -z "$CLAUDE_API_KEY" ) ]]; then
  echo "[WARN] claude is selected but HONUA_DEVOPS_CLAUDE_MODEL/API_KEY are still empty." >&2
fi

if [[ "$RUN_PREFLIGHT" == "true" ]]; then
  echo "Running preflight with generated env..."
  if [[ "$output_basename" == ".env" || "$output_basename" == ".env.local" ]]; then
    output_directory="$(dirname "$OUTPUT_PATH")"
    (
      cd "$output_directory"
      dotnet run --project "$REPO_ROOT/src/Honua.DevOps.Agent" -- --preflight
    )
  else
    (
      cd "$REPO_ROOT"
      set -a
      # shellcheck disable=SC1090
      source "$OUTPUT_PATH"
      set +a
      dotnet run --project src/Honua.DevOps.Agent -- --preflight
    )
  fi
else
  echo "Next step: fill in provider credentials if needed, then run:"
  echo "  dotnet run --project src/Honua.DevOps.Agent -- --preflight"
fi
